---
title: "Balancing"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
    fig_width: 7
    fig_height: 3
    fig_caption: true
    includes:
      in_header: "../../inst/_x3d_header.html"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Balancing}
  %\VignetteEncoding{UTF-8}
---

```{r demo, message=FALSE, echo=FALSE}
library(knitr)
library(terms)
options(cli.num_colors = 1)
theme_set(theme_grey())
opts_chunk$set(echo = FALSE, warning =FALSE,
               message=FALSE, comment='', 
               tidy=FALSE, cache = FALSE)
do.call(read_chunk, list(path = "_run.R"))
```

## Objective

This example illustrates the effect of balancing as described by Stout et al. We compare the far-field spectra for a dimer of large silver spheres with a small gap, with and without the `DisableStoutBalancing` keyword. 

This simulation uses the following `input` files 

```{R tpl}
```

(with and without the keyword).

```{r show_cluster, echo=FALSE, results='asis', message=FALSE}
library(terms)
cat('  <style>
.x3d_scene {
float:right;
margin:0em;
 }
  </style>')

ge <- get_geometry('input1')
cl <- cluster_geometry(ge)
terms::x3d_scene(cl, viewpoint=c(0,0,300), width = "200px", height = "150px") 
```

```{r read, cache=FALSE}
```


```{r oa}
```


-----

```{r cleanup}
```
_Last run: `r format(Sys.time(), '%d %B, %Y')`_
