---
title: "Near-field spectrum"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4
    fig_caption: true
    includes:
      in_header: "../../inst/_x3d_header.html"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Near-field spectrum}
  %\VignetteEncoding{UTF-8}
---

```{r demo, message=FALSE, echo=FALSE}
library(knitr)
library(terms)
options(cli.num_colors = 1)
theme_set(egg::theme_article())
opts_chunk$set(echo = FALSE, warning =FALSE,
               message=FALSE, comment='', 
               tidy=FALSE, cache = FALSE)
do.call(read_chunk, list(path = "_run.R"))
```

## Objective

This example illustrates the calculation of near-field calculations for multiple wavelengths. The structure consists of two gold spheres in water. The wavelength is varied from 400 to 800 nm, and we map the normalised local degree of chirality around the structure.

```{r show_cluster, echo=FALSE, results='asis', message=FALSE}
library(terms)
cat('  <style>
.x3d_scene {
float:right;
margin:0em;
 }
  </style>')

ge <- get_geometry('input')
cl <- cluster_geometry(ge)
terms::x3d_scene(cl, viewpoint=c(0,0,150), width = "200px", height = "150px") 
```

This simulation uses the following `input` file
```{bash input}
cat input
```

```{r read}
```

## Intensity

```{r intensity,fig.height=2}
```

## LDOC

```{r ldoc,fig.height=2}
```

-----

```{r cleanup}
```
_Last run: `r format(Sys.time(), '%d %B, %Y')`_
