---
title: "Spherical to cartesian multipole transformation"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4
    fig_caption: true
    includes:
      in_header: "../../inst/_x3d_header.html"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Spherical to cartesian multipole transformation}
  %\VignetteEncoding{UTF-8}
---

```{r demo, message=FALSE, echo=FALSE}
library(terms)
library(gridExtra)
# library(reshape2)
# library(purrr)
library(ggplot2)
library(egg)
# library(grid)
# library(readr)

library(knitr)
library(terms)
options(cli.num_colors = 1)
theme_set(egg::theme_article())
opts_chunk$set(echo = FALSE, warning =FALSE,
               message=FALSE, comment='', 
               tidy=FALSE, cache = FALSE)
do.call(read_chunk, list(path = "_run.R"))
```


This example illustrates the conversion from spherical to cartesian multipoles for the collective T-matrix of a cluster, following Mun et al. (Describing Meta-Atoms Using the Exact Higher-Order Polarizability Tensors, ACS Photonics 2020, 7, 1153−1162).


```{r show_cluster, echo=FALSE, results='asis', message=FALSE}
library(terms)
cat('  <style>
.x3d_scene {
float:right;
margin:0em;
 }
  </style>')

ge <- get_geometry('input_EE1')
cl <- cluster_geometry(ge)
terms::x3d_scene(cl, viewpoint=c(0,0,200), width = "200px", height = "150px", default_material='gold')
```

```{r load, cache=FALSE}
```

```{r collective}
```


-----

```{r cleanup}
```
_Last run: `r format(Sys.time(), '%d %B, %Y')`_
